In [ ]:
#Nested Lists

In [ ]:
a=[11,12,15,22]
a.pop(3)

In [ ]:
student_roll_nos=[32,22,55,63]
student_names=['srinath','chanikya','yasoda']

abc=zip(student_roll_nos,student_names)
for(i,j)

In [ ]:
#TUPLES

In [7]:
#Dict
abc={"English":"Hi","Hindi":"Namaste"}


In [8]:
lambda(x,y for x in )

SyntaxError: invalid syntax (<ipython-input-8-a338ab670271>, line 1)

In [18]:
#How to access nested list

In [15]:
student={'name':'John','rollno':22,'marks':[[0,9],[22,26,28]]}

In [17]:
student['marks'][1][1]

26

In [35]:
#SET: Its an unordered collection
#denotion is similar to dictionary but these are not key value pairs

m={'m','a',243,243}
m2={'m','a',243,243}

In [36]:
m

{243, 'a', 'm'}

In [37]:
unique(m1)

NameError: name 'unique' is not defined

In [38]:
list(set(m2))

[243, 'm', 'a']

In [39]:
m3={'m','a',243,243,1,1}

In [40]:
set(m3)

{1, 243, 'a', 'm'}

In [41]:
list(set(m3))

[1, 243, 'm', 'a']

In [45]:
    marks=[56,23,89,33,67]
    for i in marks:
        if (i<35):
            print('fail')
        elif i<60 & i>=35:
            print('pass')
        else:
            print('first class')

first class
fail
first class
fail
first class


In [47]:
for i in marks:
    if marks[i] >= 60:
        print("First Class")
    elif marks[i] <60 & marks[i] >= 35:
        print("Pass")
    else:
        print("Fail")

IndexError: list index out of range

In [1]:
students=[[i,j,k] for (i,j,k) in zip(student_names,)]

NameError: name 'student_names' is not defined

In [6]:
data=[1,2,3,4,5,6]
for i in data:
    if i%2==0:
        print('Even Number is ',i)
    else:
        print('Odd Number is ',i)

Odd Number 1
Even Number 2
Odd Number 3
Even Number 4
Odd Number 5
Even Number 6


In [7]:
for i in range(len(data)):
    if data[i]%2==0:
        print('Even number')
    else:
        print('Odd Number')
    

Odd Number
Even number
Odd Number
Even number
Odd Number
Even number


In [8]:
import numpy as np
np_array=np.random.random(2)

In [10]:
np_array=np.random.random(3)
np_array

array([0.4424681 , 0.41639278, 0.11588892])

In [11]:
import random

In [12]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
print(np.linspace(0,100,80))

[  0.           1.26582278   2.53164557   3.79746835   5.06329114
   6.32911392   7.59493671   8.86075949  10.12658228  11.39240506
  12.65822785  13.92405063  15.18987342  16.4556962   17.72151899
  18.98734177  20.25316456  21.51898734  22.78481013  24.05063291
  25.3164557   26.58227848  27.84810127  29.11392405  30.37974684
  31.64556962  32.91139241  34.17721519  35.44303797  36.70886076
  37.97468354  39.24050633  40.50632911  41.7721519   43.03797468
  44.30379747  45.56962025  46.83544304  48.10126582  49.36708861
  50.63291139  51.89873418  53.16455696  54.43037975  55.69620253
  56.96202532  58.2278481   59.49367089  60.75949367  62.02531646
  63.29113924  64.55696203  65.82278481  67.08860759  68.35443038
  69.62025316  70.88607595  72.15189873  73.41772152  74.6835443
  75.94936709  77.21518987  78.48101266  79.74683544  81.01265823
  82.27848101  83.5443038   84.81012658  86.07594937  87.34177215
  88.60759494  89.87341772  91.13924051  92.40506329  93.67088608
  94.936708

In [16]:
print(np.arange(0,100,10))

[ 0 10 20 30 40 50 60 70 80 90]


In [20]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [21]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [24]:
arr[1,0:2]

array([4, 5])

In [25]:
arr[2,1]

8

In [27]:
np.arange(25).reshape(5,2,5)

ValueError: cannot reshape array of size 25 into shape (5,2,5)

##FUNCTIONS

In [22]:
def is_leap(year):
    leap = False
    y=year
    if y>=1900 & y<=100000:
        if y%4==0:
            if (y%100==0):
                if (y%400== 0):
                    leap=True
                else:
                    leap=False
            else:
                leap=True
        else:
            leap=False


    
    # Write your logic here
    
    return leap

year = int(input())
is_leap(year)

1992


True

In [36]:
n=int(input())
for i in range(n+1):
    print(i,end="")


3
0123