## Numpy

NumPy or Numerical Python, is the fundamental package required for high performance scientific computing and data analysis.

    A powerful N-dimensional array object


### Why Numpy

    Memory Efficient
    Vectorized operations

https://www.scipy.org/scipylib/faq.html#what-advantages-do-numpy-arrays-offer-over-nested-python-lists

In [1]:
#list, set, tuple, dictionary, if-loop, for loop, while loop, break and continue, variables, containers, operators, string, numbers

#libraries that help us to do the tasks

#installing library
!pip install library_name


ERROR: Could not find a version that satisfies the requirement library_name (from versions: none)
ERROR: No matching distribution found for library_name


In [2]:
i



NameError: name 'i' is not defined

In [13]:
# import numpy as np
# import random
# np_array = np.random.random(1000)

# normal disturbution [-20, +20] 99.6% [-6 to +6]
# np_array

# python_list = random.sample(range(1000), 1000)
# python_list

import numpy as np
import random

np_array=np.random.random(100)
python_list=random.sample(range(100),10)
python_list

[19, 44, 96, 65, 11, 56, 86, 50, 14, 10]

In [ ]:
import timeit
import numpy as np #[Alias form]
import random



np_array = np.random.random(1000)
python_list = random.sample(range(1000), 1000)


def python_code():
    return [val-32 for val in python_list]


def numpy_code():
    return np_array-32

n = 1000

t_python = timeit.timeit(python_code, number=n)
t_numpy = timeit.timeit(numpy_code, number=n)

print('Time python', t_python)
print('Time numpy', t_numpy)
print('Speed Comparision', t_python/t_numpy)

Time python 0.16143963098875247
Time numpy 0.006095745018683374
Speed Comparision 26.48398686197376


In [ ]:
import timeit
import numpy as np #[Alias form]
import random



np_array = np.random.random(1000)
python_list = random.sample(range(1000), 1000)


def python_code_test():
    return [val-32 for val in python_list]


def numpy_code():
    return np_array-32

n = 1000

t_python = timeit.timeit(python_code, number=n)
t_numpy = timeit.timeit(numpy_code, number=n)

print('Time python', t_python)
print('Time numpy', t_numpy)
print('Speed Comparision', t_python/t_numpy)

Time python 0.16143963098875247
Time numpy 0.006095745018683374
Speed Comparision 26.48398686197376


In [20]:
import timeit
import numpy as np
import random

np_array=np.random.random(1000)
python_list=random.sample(range(1000),1000)

def python_code():
    return [val-32 for val in python_list]

def numpy_code():
    return np_array-32
n=1000
t_python=timeit.timeit(python_code,number=n)
t_array=timeit.timeit(numpy_code,number=n)

print('Time numpy',t_array)
print('Time python',t_python)

print('Speed Comparision',t_python/t_array)

Time numpy 0.0022759000000860397
Time python 0.14225229999988187
Speed Comparision 62.503756753154384



### ARRAY:  Array is a group of elements, of same data type, indexed by tuple of non-negative integers.

Array: An array is a contiguous block of memory consisting of elements of some type (e.g. integers).
You cannot change the size of an array once it is created.
It therefore follows that each integer element in an array has a fixed size, e.g. 4 bytes.

List: Python list is an array of pointers to Python objects (an "array" of addresses), at least 4 bytes per pointer plus 16 bytes for even the smallest Python object


#### Create a rank 1 array (1 dimension)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,8.9,9]) 
arr

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 8.9, 9. ])

#### Check the datatype

In [ ]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

float64
1
(10,)


### Rank 2 array

In [23]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
arr.ndim
print(arr.ndim)
print(arr.shape)

2
(4, 3)


### Different functions to create array

In [ ]:
np.arange(900,1000,10) #Array of range of numbers from 0 to 9

array([900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

In [145]:
a=np.zeros((1,10)) #Array of all zeros
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,3)) #Array of all ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
np.random.random((5,3)) #Array of random numbers

array([[ 0.8368918 ,  0.4613682 ,  0.82872401],
       [ 0.77424341,  0.15899729,  0.07205358],
       [ 0.30614151,  0.93399446,  0.80473179],
       [ 0.00638184,  0.24916616,  0.79239137],
       [ 0.1076441 ,  0.57137641,  0.26882581]])

In [ ]:
#an array of equally spaced values between start, end
print(np.linspace(0,99,80))
print(np.arange(0,100,10)) 

[ 0.          1.25316456  2.50632911  3.75949367  5.01265823  6.26582278
  7.51898734  8.7721519  10.02531646 11.27848101 12.53164557 13.78481013
 15.03797468 16.29113924 17.5443038  18.79746835 20.05063291 21.30379747
 22.55696203 23.81012658 25.06329114 26.3164557  27.56962025 28.82278481
 30.07594937 31.32911392 32.58227848 33.83544304 35.08860759 36.34177215
 37.59493671 38.84810127 40.10126582 41.35443038 42.60759494 43.86075949
 45.11392405 46.36708861 47.62025316 48.87341772 50.12658228 51.37974684
 52.63291139 53.88607595 55.13924051 56.39240506 57.64556962 58.89873418
 60.15189873 61.40506329 62.65822785 63.91139241 65.16455696 66.41772152
 67.67088608 68.92405063 70.17721519 71.43037975 72.6835443  73.93670886
 75.18987342 76.44303797 77.69620253 78.94936709 80.20253165 81.4556962
 82.70886076 83.96202532 85.21518987 86.46835443 87.72151899 88.97468354
 90.2278481  91.48101266 92.73417722 93.98734177 95.24050633 96.49367089
 97.74683544 99.        ]
[ 0 10 20 30 40 50 60 70 8

In [ ]:
given numbrs between  0 to 100, print output 0,10,20,30,40,50,60,70,80,90
make 80 numbers with equal spacing between the range of 0 to 100, 

0, 0.8, 1.6, 2.4, 3,2, 4.0


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Data types
https://docs.scipy.org/doc/numpy/user/basics.types.html

    Integer: int (i),
    Unsigned integer: uint (u),
    Single precision float: float (f),
    Double precision float: double (d),
    Boolean: bool (b),
    Complex: D,
    String: S,
    Unicode: U

In [ ]:
np.sctypes

{'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, bytes, str, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

In [32]:
int_arr = np.array([[-1,2,3,4], [5,-6,7,8]])
int_arr
#arr.dtype

array([[-1,  2,  3,  4],
       [ 5, -6,  7,  8]])

In [33]:
u_int_arr = np.array([[1,2,3,4], [5,6,7,8]], dtype = 'uint')
u_int_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=uint32)

In [34]:
bool_arr = np.array([True, True, False])
bool_arr

array([ True,  True, False])

#### Explicitly convert or cast an array from one dtype to another

In [35]:
int_arr = int_arr.astype(np.float64)
int_arr.dtype

dtype('float64')

#### String vs Object:
The length of the string is not fixed. So instead of saving the bytes of strings in the ndarray directly, Pandas uses object ndarray, which save pointers to objects.

Helps in case you need to modify the content of a large array without prior knowledge about the maximum length of the strings

In [36]:
a = np.array(['apples', 'banananas', 'mangoes'], dtype = 'str')
a #"seven-character string"

array(['apples', 'banananas', 'mangoes'], dtype='<U9')

In [38]:
a[1] = 'bananananas'
a

array(['apples', 'banananan', 'mangoes'], dtype='<U9')

In [39]:
a = np.array(['apples', 'bananas', 'mangoes'], dtype = object)
a[2] = 'bananananas'
a

array(['apples', 'bananas', 'bananananas'], dtype=object)

In [59]:
import pandas as pd
deliveries=pd.read_csv('/ipl/deliveries.csv')
#deliveries.dtypes
deliveries.head()

FileNotFoundError: [Errno 2] File /ipl/deliveries.csv does not exist: '/ipl/deliveries.csv'

### Unary operations: one input

In [47]:
a = np.array([9,17,51,4,25,64,36]) #
a.sum()

# 0-5:  9    9
# 5-10: 17   26
# 10-15: 51  77
# 4


206

In [48]:
a.max()

64

In [49]:
a.min()

4

In [50]:
a.cumsum()

array([  9,  26,  77,  81, 106, 170, 206], dtype=int32)

In [51]:
deliveries.groupby(['match_id','batting_team', 'batsman']).batsman_runs.sum().reset_index().head(20)

NameError: name 'deliveries' is not defined

### Shape Manipulation:

#### Reshape, Traspose, ravel

In [ ]:
import numpy as np
arr = np.array([3,5,7,13,1,9, 19,12,5,16,31,6])
arr = arr.reshape(4,3)
arr

array([[ 3,  5,  7],
       [13,  1,  9],
       [19, 12,  5],
       [16, 31,  6]])

In [ ]:
arr.T 
#https://stackoverflow.com/questions/42796548/plot-per-row-in-pandas#comment72707802_42796548

array([[ 3, 13, 19, 16],
       [ 5,  1, 12, 31],
       [ 7,  9,  5,  6]])

In [ ]:
arr.ravel()

array([ 3,  5,  7, 13,  1,  9, 19, 12,  5, 16, 31,  6])

### Array Indexing

In [52]:
arr = np.arange(10)
arr[2:8]
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
arr[:3] = 100
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [54]:
arr_slice = arr[6:]
arr_slice[:] = -100
arr_slice

array([-100, -100, -100, -100])

In [ ]:
arr

array([   0,    1,    2,    3,    4,    5, -100, -100, -100, -100])

#### Indexing higher dimentional array

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1,:2] #array([4,5]) #rows [0:1], columns [0:2]

array([4, 5])

In [ ]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
print(np.arange(24))


#2 dimension: 4x6, 6x4, 3x8, 8x3, 2x12, 12x2
#3 dimesion: 2x4x3, 6x2x2

print(np.arange(24).reshape(6,2,2)) #30 elements

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [ ]:
threed_arr = np.arange(24).reshape(2,3,4)
threed_arr#[1:, :2, :2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Boolean Indexing

In [55]:
arr = np.array([9,5,2,16,7,0,4])
arr > 5

array([ True, False, False,  True,  True, False, False])

In [56]:
arr[(arr > 5)&(arr < 9)]

array([7])

In [57]:
deliveries[(deliveries.total_runs == 6) | (deliveries.total_runs == 4)][:5]

NameError: name 'deliveries' is not defined

In [ ]:
arr = np.array([[6,4,3,8], [9,0,2,5]])
arr[arr >4]
arr[(arr >4) & (arr < 9)]

array([6, 8, 5])

In [61]:
arr_str = np.array(['Google', 'Apple', 'Microsoft', 'Facebook','PayPal','HP', 'Linkedlin'])
arr_str == 'Microsoft'

array([False, False,  True, False, False, False, False])

In [62]:
arr_str[arr_str != 'Microsoft'] #subset of an entire set


array(['Google', 'Apple', 'Facebook', 'PayPal', 'HP', 'Linkedlin'],
      dtype='<U9')

In [67]:
arr_str[(arr_str == 'Microsoft') | (arr_str =='PayPal')]

array(['Microsoft', 'PayPal'], dtype='<U9')

In [ ]:
matches=pd.read_csv('/Users/vaishaligarg/Downloads/ipl/matches.csv')
matches.head()
matches[matches.player_of_match == 'MEK Hussey'].shape

(12, 18)

### Broadcasting

element-by-element operations on array of same shape or array and a scalar value


In [68]:
# Given two lists, quantity and rate, return a list multiplication of the two values

avg_score = [31,21,55,18,8,14,3,95,21,6]
innings_played = [8,7,10,2,8,5,13,4,7,9]
#avg_score*innings_played # unsupported operand type(s) for ** or pow(): 'list' and 'list'
#total_runs = [s*i for s, i in zip(avg_score, innings_played)]
#total_runs
%timeit [q*r for q, r in zip(avg_score, innings_played)]

1.75 µs ± 212 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [70]:
avg_score=[31,21,4,23,22]
innings_played=[2,6,7,9,1]
%timeit [q*r for q,r in zip(avg_score,innings_played)]

1.17 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [71]:
avg_score = np.array(avg_score)
innings_played = np.array(innings_played)
#avg_score*innings_played
%timeit avg_score*innings_played

753 ns ± 131 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [72]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
a1+a2
a1-a2
#a1/a2

array([-4, -4, -4, -4])

In [73]:
#Try the same with
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8,9])
a1+a2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [81]:
#Here the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array. Combining the 
#4x1 array with b, which has shape (3,), yields a 4x3 array.

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a = a[:, np.newaxis]

print(a) #vector
print(b)
#a + b    

[[ 0.]
 [10.]
 [20.]
 [30.]]
[1. 2. 3.]


### Universal Functions
    Functions that operate on ndarrays in an element-by-element fashion
https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [83]:
a1 = np.array([10,2,31,45])
a2 = np.array([53,62,7,18])

np.add(a1,a2)
np.subtract(a2,a1)

array([ 43,  60, -24, -27])

In [ ]:
np.subtract(a1,a2)

array([-43, -60,  24,  27])

In [85]:
np.divide(a1,a2)

array([0.18867925, 0.03225806, 4.42857143, 2.5       ])

In [87]:
np.maximum(a1,a2)

array([53, 62, 31, 45])

In [89]:
a = np.array([1,4,9,16,25])
np.sqrt(a)

array([1., 2., 3., 4., 5.])

In [90]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [95]:
arr = np.array([6,2,0,1,5,0,7,10,0])
#np.nonzero(arr)
#arr[np.nonzero(arr)]
np.nonzero(arr)

(array([0, 1, 3, 4, 6, 7], dtype=int64),)

In [98]:
x = np.random.randn(5)
x
y=np.random.randn(7)
y

array([-2.91424548, -0.11942139,  1.17818653, -0.34237708, -1.46114902,
        0.45953295,  1.76277469])

In [100]:
np.floor(x)
np.ceil(x)

np.floor(y)
np.ceil(y)

array([-2., -0.,  2., -0., -1.,  1.,  2.])

#### Matrix multiplication

In [104]:
x = np.matrix([[10,2],[31,45]])
y = np.mat([[53,62], [7,18]])
x*y
#np.dot(x,y) # or x.dot(y)

matrix([[ 544,  656],
        [1958, 2732]])

In [101]:
x=np.matrix([[10,2],[31,22]])
x

matrix([[10,  2],
        [31, 22]])

In [ ]:
x = np.array([[10,2],[31,45]])
y = np.array([[53,62], [7,18]])
x*y

array([[530, 124],
       [217, 810]])

### np.where: ([cond], if, else)


In [105]:
x = np.random.randn(5)
y = np.random.randn(5)
x

array([-1.45303529,  0.04123108,  1.61449   ,  0.34732252,  0.6010793 ])

In [106]:
y

array([ 0.70156118, -2.05016108,  0.35183078, -0.19475827, -1.42619258])

In [107]:
np.where(x > 0, x, y)

array([0.70156118, 0.04123108, 1.61449   , 0.34732252, 0.6010793 ])

In [ ]:
matches.head()
matches1 = matches[['id', 'season', 'team1', 'team2', 'win_by_runs', 'win_by_wickets']].copy()
matches1.head()

id  season                  team1                        team2  \
0   1    2008  Kolkata Knight Riders  Royal Challengers Bangalore   
1   2    2008    Chennai Super Kings              Kings XI Punjab   
2   3    2008       Rajasthan Royals             Delhi Daredevils   
3   4    2008         Mumbai Indians  Royal Challengers Bangalore   
4   5    2008        Deccan Chargers        Kolkata Knight Riders   

   win_by_runs  win_by_wickets  
0          140               0  
1           33               0  
2            0               9  
3            0               5  
4            0               5

In [ ]:
matches1['level'] = np.where((matches1.win_by_runs < 20) , 'Super exciting!', 'Expected')
matches1.head()

id  season                  team1                        team2  \
0   1    2008  Kolkata Knight Riders  Royal Challengers Bangalore   
1   2    2008    Chennai Super Kings              Kings XI Punjab   
2   3    2008       Rajasthan Royals             Delhi Daredevils   
3   4    2008         Mumbai Indians  Royal Challengers Bangalore   
4   5    2008        Deccan Chargers        Kolkata Knight Riders   

   win_by_runs  win_by_wickets            level  
0          140               0         Expected  
1           33               0         Expected  
2            0               9  Super exciting!  
3            0               5  Super exciting!  
4            0               5  Super exciting!

In [ ]:
matches1['level'] = np.where((matches1.win_by_runs < 20) & (matches1.win_by_wickets < 3), 'Super exciting!', 'Expected')
matches1.head()

id  season                  team1                        team2  \
0   1    2008  Kolkata Knight Riders  Royal Challengers Bangalore   
1   2    2008    Chennai Super Kings              Kings XI Punjab   
2   3    2008       Rajasthan Royals             Delhi Daredevils   
3   4    2008         Mumbai Indians  Royal Challengers Bangalore   
4   5    2008        Deccan Chargers        Kolkata Knight Riders   

   win_by_runs  win_by_wickets     level  
0          140               0  Expected  
1           33               0  Expected  
2            0               9  Expected  
3            0               5  Expected  
4            0               5  Expected

### Statistical methods


In [108]:
arr = np.array([[5,9,3,6], [9,2,0,8],[8,5,6,8]])
arr

array([[5, 9, 3, 6],
       [9, 2, 0, 8],
       [8, 5, 6, 8]])

In [109]:
arr[:3,3:4] #lower bound is not covred [lower to number-1] 0,1,2,3,4,5,6,7,8,9

array([[6],
       [8],
       [8]])

#### axis 0 - across rows - rows are getting pushed together into the result - columns remain same

In [110]:
arr.mean(axis = 0)

array([7.33333333, 5.33333333, 3.        , 7.33333333])

#### axis 1 - across columns - columns are getting pushed together into the result - rows remain same

In [111]:
arr.mean(axis = 1)

array([5.75, 4.75, 6.75])

In [112]:
np.median(arr, 0)

array([8., 5., 3., 8.])

### sort(), argmax(), argmin()
    argmax: Returns the indices of the maximum values along an axis.
    argmin: Returns the indices of the minimum values along an axis.

In [113]:
arr = np.array([6,9,4,2,10,3])
arr.sort()
arr

array([ 2,  3,  4,  6,  9, 10])

In [114]:
arr = np.array([6,9,4,2,10,3])
arr.argmax() 
arr.argmin() 
arr[arr.argmin()]

2

### Stacking 

In [115]:
a = np.random.random((2,2))
a

array([[0.06765757, 0.55011681],
       [0.94651431, 0.08269325]])

In [116]:
b = np.random.random((2,2))
b

array([[0.76755249, 0.15655115],
       [0.28869345, 0.94680224]])

In [117]:
c = np.vstack((a,b))
c#.shape

array([[0.06765757, 0.55011681],
       [0.94651431, 0.08269325],
       [0.76755249, 0.15655115],
       [0.28869345, 0.94680224]])

In [118]:
d = np.hstack((a,b))
d#.shape

array([[0.06765757, 0.55011681, 0.76755249, 0.15655115],
       [0.94651431, 0.08269325, 0.28869345, 0.94680224]])

In [119]:
np.concatenate((a,b))
np.concatenate((a,b), axis = 1) #pd.concat([df1, df2], axis = 1)

array([[0.06765757, 0.55011681, 0.76755249, 0.15655115],
       [0.94651431, 0.08269325, 0.28869345, 0.94680224]])

### Splitting

In [120]:
np.hsplit(c, 2)

[array([[0.06765757],
        [0.94651431],
        [0.76755249],
        [0.28869345]]),
 array([[0.55011681],
        [0.08269325],
        [0.15655115],
        [0.94680224]])]

In [121]:
np.vsplit(c, 2)

[array([[0.06765757, 0.55011681],
        [0.94651431, 0.08269325]]),
 array([[0.76755249, 0.15655115],
        [0.28869345, 0.94680224]])]

### Copies and views

In [123]:
a = np.arange(10)
b = a #view
b is a #identity operator

True

In [124]:
b*=2
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [125]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
a +=5
b

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [127]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [128]:
a = np.arange(10)
b = a.copy()
b is a

False

In [129]:
b*=2

In [130]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
a+=10

In [132]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [141]:

import numpy as np
a = np.array([8,5,3,1,9,7,4,2,6,8,2,0])
a = a.reshape(2,6)
a.mean() #mean of the entire array
a.mean(axis = 0) #mean along axis 0 - for each column
#a.mean(axis = 1) #along axis 1

array([6. , 3.5, 4.5, 4.5, 5.5, 3.5])

In [142]:
a1 = np.array([9,0,5,0,2,1])
a1[np.nonzero(a1)]
a[-1]

array([4, 2, 6, 8, 2, 0])

In [140]:
import numpy as np
a=np.array([8,4,6,3,1,7,8,99])
a=a.reshape(2,4)
print(a)
print(a.mean())
a.mean(axis=0)

[[ 8  4  6  3]
 [ 1  7  8 99]]
17.0


array([ 4.5,  5.5,  7. , 51. ])