In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)


In [ ]:
#Initial Placeholders
np.zeros((2,3))

In [ ]:
np.ones((2,3,4),dtype=int)

In [ ]:
d=np.arange(10,25,5)
d

In [ ]:
np.linspace(0,2,9)

In [ ]:
e=np.full((2,2),7)
e

In [ ]:
f=np.eye(2)
f

In [ ]:
np.random.random((2,2))

In [ ]:
np.empty((3,2))

In [ ]:
#Input & Output
#Saving and loading Text files
a=np.genfromtxt("G:\\JOBIFY\\PythonInputOutput\\myfile.txt",dtype=str,delimiter='\t')
a

In [ ]:
np.savetxt("myarray.txt",a,delimiter=" ")

In [ ]:
file=open("G:\\JOBIFY\\PythonInputOutput\\myfile.txt",'r')

In [ ]:
file.readlines()

In [ ]:
#Saving and loading on Disk
np.save('my array',a)
np.savez('array.npz',a,b)
np.load('my_array.npy')

In [ ]:
# from tempfile import TemporaryFile
# outfile=TemporaryFile()
# np.load(outfile)
# X=np.arange(10)
# np.save(outfile,X)
# np.load(outfile,encoding='latin1',allow_pickle=True).item()
# with open('test.npy','wb') as f:
#     np.save(f,np.array([1,2]))
#     np.save(f,np.array([1,3]))

# with open('test.npy','wb') as f:
#     a=np.load(f)
#     b=np.load(f)

# print(a,b)

# #[1 2] [1 3]


In [ ]:
#DataTypes
np.int64
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_


In [ ]:
#Inspecting your Array
a.shape
len(a)
b.ndim
e.size
b.dtype.name
print(b.dtype)
b.astype(int)
print(b.dtype)

In [ ]:
#Asking for help
np.info(np.ndarray.dtype)

In [ ]:
#Array Mathematics
#Arithmetic operations

np.add(a,b)

In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
np.divide(a,b)

In [ ]:
np.exp(b)

In [ ]:
np.sqrt(b)

In [ ]:
np.sin(a)

In [ ]:
np.cos(a)

In [ ]:
np.log(a)

In [ ]:
np.tan(a)

In [ ]:
np.dot(e,f)

In [139]:
#Comparision
a==b

array([[False,  True,  True],
       [False, False, False]])

In [140]:
a<2

array([ True, False, False])

In [142]:
np.array_equal(a,b)

False

In [154]:
#AggregateFunctions
a.sum()
a.min()
b.max(axis=0)
b.cumsum(axis=1)
a.mean()
#b.median()
#a.corrcoef()
np.std(a)

0.816496580927726

In [149]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [159]:
h=a.view()
h

array([1, 2, 3])

In [160]:
np.copy(a)

array([1, 2, 3])

In [164]:
h=a.copy()

In [172]:
#Sorting Arrays
a.sort()
print(c.sort(axis=0))


None


In [174]:
#Subsetting, Slicing, indexing
a[2]
b[1,2]

6.0

In [177]:
a[a<4]

array([1, 2, 3])

In [180]:
#Array Manipulations
#Transposing a matrix

i=np.transpose(b)
print(i)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [181]:
b.ravel() #flattening the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [187]:
b.reshape(3,-2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [192]:
#Adding/Removing Elements
h.resize((2,6))
np.append(h,f)

array([1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       <_io.BufferedWriter name='test.npy'>], dtype=object)

In [193]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [201]:
np.insert(a,2,6)

array([1, 2, 6, 3])

In [204]:
np.delete(a,[1])

array([1, 3])

In [208]:
#combining arrays
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [213]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [214]:
e

array([[7, 7],
       [7, 7]])

In [217]:
f=np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [218]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [228]:
#splitting arrays
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [229]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [231]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [233]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]

In [236]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [238]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])